### ISSUE TITLE
Create Items should use AJAX

### ISSUE THREAD

**Issue by adamzuckerberg** [adamwohlberg/ratestuf_on_rails#2]
When a user searches for a new item (that doesn't yet exist in the db) and the use is logged in, the item is created. 

This should be AJAX not HTTP.

**Comment by topher6345** [comment]
If creation is done via AJAX the url will have to look like this

`http://localhost:3000/?utf8=%E2%9C%93&search=uber`

`localhost:3000/#utf8=%E2%9C%93&search=uber`

notice the hash `#` in the url, then you have to process the arguments in javascript
